[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_WEBPACK_USEPOLLING = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

